[package]
name = "yarnspinner_core"
version = "0.5.0"
edition = "2021"
repository = "https://github.com/YarnSpinnerTool/YarnSpinner-Rust"
homepage = "https://docs.yarnspinner.dev/"
categories = ["game-development", "compilers"]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
license = "MIT OR Apache-2.0"
description = "Core concepts for Yarn Spinner for Rust, the friendly tool for writing game dialogue"

[features]
default = ["std"]
std = ["prost/std"]
serde = ["dep:serde", "hashbrown/serde"]

[dependencies]
prost = { version = "0.12", default-features = false, features = [
    "prost-derive",
] }
serde = { version = "1", features = ["derive"], optional = true }
variadics_please = "1.1.0"
hashbrown = "0.15.2"

[dev-dependencies]
static_assertions = "1.1.0"

[lints.clippy]
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
